on: 
  push:
    branches:
        - main
  pull_request:

name: Unit tests
jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v2 # for grpc
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
  e2e:
    name: e2e test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v2 # for grpc
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Start Ruuster server
        run: cargo run --bin server
      - name: Run e2e test
        env: 
          RUUSTER_BUILD_DIR: target/debug
          RUUSTER_HOME_DIR: .
        run: RUST_LOG=info $RUUSTER_BUILD_DIR/run_scenario  --server-addr "http://127.0.0.1:50051" --config-file "apps/src/test_client/scenarios/all_consumers.json"   --builder-bin "$RUUSTER_BUILD_DIR/scenario_builder"   --consumer-bin "$RUUSTER_BUILD_DIR/consumer" --producer-bin "$RUUSTER_BUILD_DIR/producer"
